<a href="https://colab.research.google.com/github/HAFSAHASSAN517/PYTHON_ASSIGNMENT/blob/main/assin5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Create a NumPy array of 20 random integers; compute mean/median/std; reshape to 4×5

import numpy as np
new_array = np.random.randint(1,101,20)
#finding mean
array_mean=np.mean(new_array)
array_median = np.median(new_array)
array_std = np.std(new_array)
array_reshape = new_array.reshape(4,5)
print(array_mean)
print(array_median)
print(array_std)
print(array_reshape)

42.25
35.5
29.133957849904295
[[ 39  42  15  36  65]
 [ 67  17  63  94   8]
 [ 16  54  26  96 100]
 [ 33   5  14  20  35]]


In [11]:
import pandas as pd
data = { "names" : ["Nova",
"Orion",
"Zephyr",
"Aura",
"Phoenix",
"Atlas",
"Celeste",
"Echo",
"Solstice",
"Kai"],
   "age":[20,24,
21,23,22,20,24,21,23,22
]
,"score" :[85, 92, 47, 78, 63, 95, 54,88, 71, 60] }
df = pd.DataFrame(data)
print(df)
print("Students STATS")
print(df.describe())

      names  age  score
0      Nova   20     85
1     Orion   24     92
2    Zephyr   21     47
3      Aura   23     78
4   Phoenix   22     63
5     Atlas   20     95
6   Celeste   24     54
7      Echo   21     88
8  Solstice   23     71
9       Kai   22     60
Students STATS
             age      score
count  10.000000  10.000000
mean   22.000000  73.300000
std     1.490712  16.826236
min    20.000000  47.000000
25%    21.000000  60.750000
50%    22.000000  74.500000
75%    23.000000  87.250000
max    24.000000  95.000000


In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [18]:
import pandas as pd

# Paste your copied path inside the quotes
file_path = '/content/drive/MyDrive/Colab Notebooks/student_scores.csv'


df = pd.read_csv(file_path)
print(df.columns)
filteredd_scores = df[df["Score"]>70]
print(filteredd_scores)

Index(['Student Name', 'Score', 'Grade'], dtype='object')
          Student Name  Score Grade
0           Emma Smith     95     A
1         Liam Johnson     88     B
2      Olivia Williams     72     C
3           Noah Brown     91     A
5         Ethan Garcia     78     C
6        Sophia Miller     85     B
7          Mason Davis     99     A
9     William Martinez     81     B
10       Mia Hernandez     90     A
12  Charlotte Gonzalez     75     C
13     Benjamin Wilson     84     B
14     Amelia Anderson     92     A
16       Harper Taylor     77     C
17     Alexander Moore     89     B
18      Evelyn Jackson     94     A
19         Ethan White     71     C


In [34]:
import pandas as pd
filepathh = '/content/drive/MyDrive/Colab Notebooks/_data.csv'

def run_data_pipeline(input_path:str,output_path:str,summary_path:str):
 df  = pd.read_csv(input_path)
 numeric_col =df.select_dtypes(include=["number"]).columns
 text_cols = df.select_dtypes(include=["object","category"]).columns
 if len(numeric_col)>0:
   df[numeric_col]= df[numeric_col].fillna(df[numeric_col].median())
 if len(text_cols) >0:
   df[text_cols] = df[text_cols].fillna("unknown")

 df = df.dropna(how ="all")
 df.to_csv(output_path ,index = False)

 group_cols =text_cols[0] if len(text_cols)>0 else df.columns[0]

 firstnum_col = (numeric_col[0]
                 if len(numeric_col)>0 else (df.columns[1] if len(df.columns)> 1 else df.columns[0]))

 sum_df = (df.groupby(group_cols)[firstnum_col].agg(totalcount='count'
 ,  mean_value ='mean',
   max_val='max'
  ,min_val='min').reset_index())
 sum_df.to_csv(summary_path,index=False)
 print(f"Pipeline complete!\n - Cleaned data -> {output_path}\n - Summary report -> {summary_path}")

 run_data_pipeline('input_data.csv', 'cleaned_data.csv', 'summary_report.csv')


In [37]:

import pandas as pd
dataframe={
    "name":["a","b","c","d","e"],
    "scores":[13,12,15,14,3]
}
df = pd.DataFrame(dataframe)
stats ={
    "metrics":["mean","median","max","min"]
    , "value":[
        df["scores"].mean(),
        df["scores"].median(),
        df["scores"].min(),
        df["scores"].max()

    ]
}
summary_stats = pd.DataFrame(stats)
summary_stats.to_csv("summary_stats_report", index=False)
print("original data")
print(df)
print("new data")
print(summary_stats)

original data
  name  scores
0    a      13
1    b      12
2    c      15
3    d      14
4    e       3
new data
  metrics  value
0    mean   11.4
1  median   13.0
2     max    3.0
3     min   15.0
